port: 3000

db:
  type: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  pass: ${DB_PASS}
  db: ${DB_NAME}
  ssl: true

ssl:
  enabled: false
  port: 3443
  provider: custom
  format: pem
  key: path/to/key.pem
  cert: path/to/cert.pem
  pfx: path/to/cert.pfx
  passphrase: null
  dhparam: null
  domain: wiki.yourdomain.com
  subscriberEmail: admin@example.com

pool:
  # min: 2
  # max: 10

bindIP: 0.0.0.0

logLevel: info

logFormat: default
offline: false
ha: false
dataPath: ./data
bodyParserLimit: 5mb 